# Generated by Django 3.0.1 on 2022-01-05 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionlisting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, default='Other', max_length=64, null=True),
        ),
    ]
