# Generated by Django 3.0.1 on 2022-01-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220106_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='users',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
