# Generated by Django 3.0.1 on 2022-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.IntegerField(default=-1),
        ),
    ]
