# Generated by Django 3.0.1 on 2022-01-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlisting_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='user_watchlist',
        ),
    ]
