# Generated by Django 3.0.1 on 2022-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
