# Generated by Django 3.0.1 on 2022-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20220108_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Comments'),
        ),
    ]
