# Generated by Django 3.0.1 on 2022-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20220108_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Category'),
        ),
    ]
