# Generated by Django 3.0.1 on 2022-01-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220109_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='auctions', to='auctions.Category'),
        ),
    ]
